/// 更新说明文本处理工具。
class UpdateChangelogText {
  const UpdateChangelogText._();

  /// 将 Release 正文拆成适合虚拟列表展示的条目。
  static List<String> releaseBodyItems(String? body) {
    final text = (body ?? '').trim();
    if (text.isEmpty) return const <String>[];

    return text
        .split(RegExp(r'\r?\n'))
        .map(_normalizeLine)
        .where((line) => line.isNotEmpty)
        .where((line) => !_isAutogeneratedChangelogLine(line))
        .toList(growable: false);
  }

  static String _normalizeLine(String line) {
    final trimmed = line.trim();
    return trimmed
        .replaceFirst(RegExp(r'^#{1,6}\s+'), '')
        .replaceFirst(RegExp(r'^[-*+]\s+'), '')
        .replaceFirst(RegExp(r'^\d+[.)]\s+'), '')
        .trim();
  }

  static bool _isAutogeneratedChangelogLine(String line) {
    final lower = line.toLowerCase();
    return lower.contains('full changelog') && lower.contains('...');
  }
}
